version: "3"
services:
  sonarqube:
    container_name: sonarqube
    image: sonarqube:8-community
    restart: always
    environment:
       SONAR_JDBC_URL: jdbc:postgresql://192.168.2.116:5432/sonarqube
       SONAR_JDBC_USERNAME: postgres
       SONAR_JDBC_PASSWORD: postgres
     # - SONAR.SEARCH.JAVAADDITIONALOPTS: -Dbootstrap.system_call_filter=false
    volumes:
      - /opt/sonarCE/data:/opt/sonarqube/data
      - /opt/sonarCE/extentions:/opt/sonarqube/extensions
      - /opt/sonarCE/logs/:/opt/sonarqube/logs
    ports:
      - "9000:9000"
